repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff
        args: ["--fix"]
        # ruff-format removed to avoid CI failures on auto-formatting; run `ruff format` locally or as a separate CI job.

  - repo: local
    hooks:
      - id: mypy
        name: mypy (uv)
        entry: uv run mypy --config-file=pyproject.toml ./
        language: system
        types: [python]
        pass_filenames: false
