repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff
        args: ["--fix"]
        # ruff-format removed to avoid CI failures on auto-formatting; run `ruff format` locally or as a separate CI job.

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        args: ["--config-file=pyproject.toml"]
        additional_dependencies: [
          # typing helpers
          "sqlalchemy-stubs>=0.4",
          "types-redis>=4.6.0.20240311",
          "types-aiobotocore[s3]>=2.7.0",
          "boto3-stubs[s3]>=1.34.0",
          # core runtime deps needed for import resolution in pre-commit's isolated env
          "sqlalchemy>=2.0.0",
          "alembic>=1.16.4",
          "pydantic>=2.11.7",
          "pydantic-settings>=2.10.1",
          "fastapi>=0.116.1",
          "starlette>=0.40.0",
          "redis>=5.0.1",
          "boto3>=1.34.0",
          "aioboto3>=12.0.0",
          "botocore>=1.34.0",
          "tenacity>=8.2.3",
          "pytest-asyncio>=0.23.5",
          "python-jose[cryptography]>=3.5.0",
          "passlib>=1.7.4",
          "celery>=5.3.6",
        ]
