repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.4
    hooks:
      - id: ruff
        args: ["--fix"]
      - id: ruff-format

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.17.0
    hooks:
      - id: mypy
        args: ["--config-file=mypy.ini"]
        additional_dependencies: [
          "sqlalchemy-stubs>=0.4",
          "types-redis>=4.6.0.20240311",
          "pydantic>=2.11.7",
          "pydantic-settings>=2.10.1",
        ]
