"""init

Revision ID: 355de92cb590
Revises: 
Create Date: 2025-07-20 18:44:38.661723

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '355de92cb590'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###